import type { AIModel } from "../../types/model-types";

/** Max input token limits from https://ai.google.dev/gemini-api/docs/models */
const MAX_INPUT_1M = 1_048_576;

export const geminiModels: AIModel[] = [
    {
        appDisplayName: "Gemini 3 Pro",
        purpose: "multimodal understanding, agentic tasks, vibe-coding",
        modelKey: "gemini-3-pro-preview",
        maxInputTokens: MAX_INPUT_1M,
        description: "The best model in the world for multimodal understanding, and our most powerful agentic and vibe-coding model yet, delivering richer visuals and deeper interactivity, all built on a foundation of state-of-the-art reasoning.",
        capabilities: {
            audioGeneration: "unsupported",
            batchApi: "optional",
            caching: "optional",
            codeExecution: "optional",
            fileSearch: "optional",
            functionCalling: "optional",
            googleMapsGrounding: "unsupported",
            imageGeneration: "unsupported",
            liveApi: "unsupported",
            structuredOutput: "optional",
            thinking: "optional",
            urlContext: "optional",
            webSearch: "optional",
        },
        specialParams: [
            {
                capability: "thinking",
                allowedValues: ["low", "high"],
                apiParamField: "thinkingLevel",
                description: "The level of thinking to use. Low is less thinking, high is more thinking.",
            },
        ],
    },
    {
        appDisplayName: "Gemini 2.5 Pro",
        purpose: "complex reasoning, code, math, STEM, large datasets",
        modelKey: "gemini-2.5-pro",
        maxInputTokens: MAX_INPUT_1M,
        description: "Our state-of-the-art thinking model, capable of reasoning over complex problems in code, math, and STEM, as well as analyzing large datasets, codebases, and documents using long context.",
        capabilities: {
            audioGeneration: "unsupported",
            batchApi: "optional",
            caching: "optional",
            codeExecution: "optional",
            fileSearch: "optional",
            functionCalling: "optional",
            googleMapsGrounding: "optional",
            imageGeneration: "unsupported",
            liveApi: "unsupported",
            structuredOutput: "optional",
            thinking: "optional",
            urlContext: "optional",
            webSearch: "optional",
        },
        specialParams: [
            {
                capability: "thinking",
                allowedValues: [-1],
                apiParamField: "thinkingBudget",
                description: "Gemini 2.5 Pro requires thinking to be enabled. Use -1 to enable thinking. -1 means the model decides how much thinking to use.",
            },
        ],
    },
    {
        appDisplayName: "Gemini 2.5 Flash",
        purpose: "price-performance, large scale processing, low-latency, high volume tasks",
        modelKey: "gemini-2.5-flash",
        maxInputTokens: MAX_INPUT_1M,
        description: "Our best model in terms of price-performance, offering well-rounded capabilities. 2.5 Flash is best for large scale processing, low-latency, high volume tasks that require thinking, and agentic use cases.",
        capabilities: {
            audioGeneration: "unsupported",
            batchApi: "optional",
            caching: "optional",
            codeExecution: "optional",
            fileSearch: "optional",
            functionCalling: "optional",
            googleMapsGrounding: "optional",
            imageGeneration: "unsupported",
            liveApi: "unsupported",
            structuredOutput: "optional",
            thinking: "optional",
            urlContext: "optional",
            webSearch: "optional",
        },
        specialParams: [
            {
                capability: "thinking",
                allowedValues: [0, -1],
                apiParamField: "thinkingBudget",
                description: "Use 0 to disable thinking. -1 means enabled and the model decides how much thinking to use.",
            },
        ],
    },
    {
        appDisplayName: "Gemini 2.5 Flash-Lite",
        purpose: "ultra-fast, cost-efficient, high throughput",
        modelKey: "gemini-2.5-flash-lite",
        maxInputTokens: MAX_INPUT_1M,
        description: "Our fastest flash model optimized for cost-efficiency and high throughput.",
        capabilities: {
            audioGeneration: "unsupported",
            batchApi: "optional",
            caching: "optional",
            codeExecution: "optional",
            fileSearch: "optional",
            functionCalling: "optional",
            googleMapsGrounding: "optional",
            imageGeneration: "unsupported",
            liveApi: "unsupported",
            structuredOutput: "optional",
            thinking: "optional",
            urlContext: "optional",
            webSearch: "optional",
        },
        specialParams: [
            {
                capability: "thinking",
                allowedValues: [0, -1],
                apiParamField: "thinkingBudget",
                description: "Use 0 to disable thinking. -1 means enabled and the model decides how much thinking to use.",
            },
        ],
    },
    {
        appDisplayName: "Gemini Flash Lite (latest)",
        purpose: "ultra-fast, cost-efficient, always current",
        modelKey: "gemini-flash-lite-latest",
        maxInputTokens: MAX_INPUT_1M,
        description: "Latest Gemini Flash Lite model—fast and cost-efficient, always pointing to the current release.",
        capabilities: {
            audioGeneration: "unsupported",
            batchApi: "optional",
            caching: "optional",
            codeExecution: "optional",
            fileSearch: "optional",
            functionCalling: "optional",
            googleMapsGrounding: "optional",
            imageGeneration: "unsupported",
            liveApi: "unsupported",
            structuredOutput: "optional",
            thinking: "optional",
            urlContext: "optional",
            webSearch: "optional",
        },
        specialParams: [
            {
                capability: "thinking",
                allowedValues: [0, -1],
                apiParamField: "thinkingBudget",
                description: "Use 0 to disable thinking. -1 means enabled and the model decides how much thinking to use.",
            },
        ],
    },
];